### ISSUE TITLE
Error building MusicStore solution

### ISSUE THREAD

**Issue by grizz0blaw** [vishwanathsrikanth/learningwsc#1] opened 2018-09-28 16:57 UTC
Good afternoon Vishwanath,

I started reading your book yesterday & got to the point in chapter 4 where we go to build the MusicStore solution after downloading it from GitHub. However when I click Build Solution, it immediately gives me the error below:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Samples\aspnetcore\musicstore\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	musicstore	C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

Sure enough, when I go to the "C:\Samples\aspnetcore\musicstore\obj" path, the only thing there is a Debug folder. I looked through the whole "C:\learningwsc-master" directory & there's also no project.assets.json file. Can you tell me what I seem to be missing? Thanks!

P.S. Not sure if this helps but when I click on the error, it takes me to the Microsoft.PackageDependencyResolution.targets file where the project.assets.json file is referenced & i posted it below:

<PropertyGroup>
    <ProjectAssetsFile Condition="'$(ProjectAssetsFile)' == ''">$(MSBuildProjectExtensionsPath)/project.assets.json</ProjectAssetsFile>
    <ProjectAssetsFile>$([MSBuild]::NormalizePath($(MSBuildProjectDirectory), $(ProjectAssetsFile)))</ProjectAssetsFile>

**Comment by sriksmachi** [comment] 2018-10-06 08:11
Hi grizz0blaw, 

First of all thanks for purchasing my book and trying out samples, I'm here to help on any issue you face until you successfully complete the book. 

I have tried to reproduce the issue, by trying to build the code under 

1. learningwsc\chapter4\completed\aspnetcore\musicstore and
2. learningwsc\chapter4\begin\aspnetcore\musicstore

The first thing you would encounter if you use latest VS is to upgrade the project to .csproj since .xproj is no longer supported. I have gone ahead and upgraded and built the solution successfully. 

One reason I see this could be possible is if you're not running VS as an administrator or you can also try other options as explained [here](https://stackoverflow.com/questions/48440223/project-assets-json-error-not-found)

Let me know if it doesn't help we can connect remotely and solve the issue. 

Thanks.

**Comment by grizz0blaw** [comment] 2018-10-10 22:36
Good evening Srikanth,

First of all sorry for not checking your name in the original post! I found out what the issue was. I ended up downloading the source as zip from here on Github. When I went & opened the musicstore solution this time I remembered that sometimes you have to right-click files & check the Unblock option. After doing this during the Open Solution option, I was able to build without any issues. Thanks again for replying & hope this helps someone down the line. Also, thank you very much for your book that helps us new folks get started in the world of containers!

**Comment by sriksmachi** [comment] 2018-10-11 10:23
Thanks so much, I will go ahead and close the issue.

Sriks,

Srikanth Machiraju

Senior Consultant Microsoft | Author | Blogger

Linked In: https://www.linkedin.com/in/vishsrik/

YouTube: Tech Talk with Sriks.

**Comment by sriksmachi** [comment] 2018-10-11 10:23
Thanks, I will close the issue, thanks again for reading my book.

**Closed as completed by sriksmachi** 2018-10-11 10:23 UTC
